-- Query với inner join
SELECT *
FROM NHANVIEN A
INNER JOIN HOADON B ON (A.MANV = B.MANV)
ORDER BY A.MANV ASC;

-- Query với left join
SELECT *
FROM NHANVIEN A
LEFT JOIN HOADON B ON (A.MANV = B.MANV)
ORDER BY A.MANV ASC;

SELECT *
FROM KHACHHANG A
LEFT JOIN HOADON B ON (A.MAKH = B.MAKH)
ORDER BY A.MAKH ASC;

-- Query với right join
SELECT *
FROM KHACHHANG A
RIGHT JOIN HOADON B ON (A.MAKH = B.MAKH)
ORDER BY A.MAKH ASC;

-- Query với full join
SELECT *
FROM KHACHHANG A, HOADON B
ORDER BY A.MAKH ASC;